"""
PerimeterX (PX) Cookie Harvester Microservice for Roblox Generator
Runs a lightweight HTTP server on port 5000.
Accepts POST requests to /get_px_cookies with JSON payload:
    {"proxy": "http://user:pass@host:port"}
Uses CloakBrowser / Playwright to load roblox.com, run PX JS, collect _px3, pxcts & other cookies.
"""

import asyncio
import json
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse
import sys

try:
    from cloakbrowser import launch_async
    USE_CLOAK = True
    print("[HARVESTER] Using CloakBrowser for high-fidelity stealth harvesting.")
except ImportError:
    from playwright.async_api import async_playwright
    USE_CLOAK = False
    print("[HARVESTER] CloakBrowser not found, falling back to standard Playwright.")

async def harvest_px_cookies(proxy_raw: str, timeout_sec: int = 35) -> dict:
    cookies_dict = {}
    if not proxy_raw:
        proxy_raw = "http://b3hinp0gir7k-country-DE-session-nxkw12-time-1:wda2lnrgtjtk@eu.nettify.xyz:8080"

    parsed = urlparse(proxy_raw)
    proxy_config = {
        "server": f"{parsed.scheme or 'http'}://{parsed.hostname}:{parsed.port}"
    }
    if parsed.username:
        proxy_config["username"] = parsed.username
    if parsed.password:
        proxy_config["password"] = parsed.password

    try:
        if USE_CLOAK:
            browser = await launch_async(
                headless=True,
                proxy=proxy_config,
                humanize=True,
            )
            context = await browser.new_context(
                viewport={"width": 1366, "height": 768},
                locale="en-US",
                timezone_id="America/New_York",
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36",
                extra_http_headers={"sec-ch-ua": '"Not(A:Brand";v="24", "Chromium";v="146", "Google Chrome";v="146"'}
            )
            page = await context.new_page()
            await page.goto("https://www.roblox.com/", wait_until="networkidle", timeout=timeout_sec * 1000)
            await page.mouse.move(150, 250)
            
            # Poll up to 15 seconds for _px3 cookie to be generated by PX JS
            cookies = []
            for _ in range(15):
                await asyncio.sleep(1)
                cookies = await context.cookies()
                if any(c.get("name") == "_px3" for c in cookies):
                    print("[HARVESTER] Successfully captured _px3 cookie!", flush=True)
                    break

            await browser.close()
        else:
            async with async_playwright() as p:
                browser = await p.chromium.launch(headless=True, proxy=proxy_config)
                context = await browser.new_context(viewport={"width": 1366, "height": 768}, locale="en-US")
                page = await context.new_page()
                await page.goto("https://www.roblox.com/", wait_until="domcontentloaded", timeout=timeout_sec * 1000)
                
                cookies = []
                for _ in range(10):
                    await asyncio.sleep(1)
                    cookies = await context.cookies()
                    if any(c.get("name") == "_px3" for c in cookies):
                        print("[HARVESTER] Successfully captured _px3 cookie!")
                        break

                await browser.close()

        for c in cookies:
            if "roblox.com" in c.get("domain", ""):
                cookies_dict[c["name"]] = c["value"]

    except Exception as exc:
        import traceback
        print(f"[HARVESTER ERROR] Exception: {exc}")
        traceback.print_exc()

    return cookies_dict

class HarvesterHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(b'{"status": "ok"}')

    def do_POST(self):
        if self.path == "/get_px_cookies":
            content_length = int(self.headers.get('Content-Length', 0))
            post_data = self.rfile.read(content_length)
            try:
                payload = json.loads(post_data.decode('utf-8'))
                proxy_raw = payload.get("proxy", "")
                
                # Run async harvesting loop
                cookies = asyncio.run(harvest_px_cookies(proxy_raw))
                
                self.send_response(200)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                response_body = json.dumps({"status": "ok", "cookies": cookies})
                self.wfile.write(response_body.encode('utf-8'))
            except Exception as e:
                self.send_response(500)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({"status": "error", "message": str(e)}).encode('utf-8'))
        else:
            self.send_response(404)
            self.end_headers()

    def do_GET(self):
        if self.path == "/health":
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({"status": "healthy"}).encode('utf-8'))
        else:
            self.send_response(404)
            self.end_headers()

def run_server(port=5000):
    server_address = ('127.0.0.1', port)
    httpd = ThreadingHTTPServer(server_address, HarvesterHandler)
    print(f"[HARVESTER] PX Cookie Harvester running on http://127.0.0.1:{port}")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n[HARVESTER] Shutting down...")
        httpd.server_close()

if __name__ == "__main__":
    port = 5000
    if len(sys.argv) > 1:
        port = int(sys.argv[1])
    run_server(port)
